TheWaterProject2/Models/EFWaterRepository.cs
using SQLitePCL;

namespace TheWaterProject2.Models
{
    public class EFWaterRepository : IWaterRepository
    {
        private WaterProjectContext2 _context;
        public EFWaterRepository(WaterProjectContext2 temp) 
        {
            _context = temp;
        }


        public IQueryable<Project> Projects => _context.Projects;
    }
}

TheWaterProject2/Models/IWaterRepository.cs
namespace TheWaterProject2.Models
{
    public interface IWaterRepository
    {
        public IQueryable<Project> Projects {  get; }
    }
}

TheWaterProject2/Models/Project.cs
using System.ComponentModel.DataAnnotations;

namespace TheWaterProject2.Models
{
    public class Project
    {
        [Key]
        public int projectId { get; set; }
        public string projectName { get; set; } = "N/A";
        public string programName { get; set; }
        public string? projectType { get; set; }
        public int projectImpactLevel { get; set; }
        public DateTime projectInstallation { get; set; }
        public string projectPhase { get; set; }
    }
}

TheWaterProject2/Models/ViewModels/PaginationInfo.cs
namespace TheWaterProject2.Models.ViewModels
{
    public class PaginationInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalNumPages => (int) (Math.Ceiling((decimal) TotalItems / ItemsPerPage));
    }
}

TheWaterProject2/Models/ViewModels/ProjectsListViewModel.cs
namespace TheWaterProject2.Models.ViewModels
{
    public class ProjectsListViewModel
    {
        public IQueryable<Project> Projects { get; set; }
        public PaginationInfo PaginationInfo { get; set; } = new PaginationInfo();
        public string? CurrentProjectType { get; set; }
    }
}

TheWaterProject2/Models/WaterProjectContext2.cs
using Microsoft.EntityFrameworkCore;

namespace TheWaterProject2.Models
{
    public class WaterProjectContext2: DbContext
    {
        public WaterProjectContext2(DbContextOptions<WaterProjectContext2> context) : base(context) { }

        public DbSet<Project> Projects { get; set; }
    }
}

TheWaterProject2/Components/ProjectTypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TheWaterProject2.Models;

namespace TheWaterProject2.Components
{
    public class ProjectTypesViewComponent: ViewComponent
    {
        private IWaterRepository _waterRepo;
        public ProjectTypesViewComponent(IWaterRepository temp) 
        {
            _waterRepo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedProjectType = RouteData?.Values["projectType"];

            var projectTypes = _waterRepo.Projects
                .Select(x => x.projectType)
                .Distinct()
                .OrderBy(x => x);

            return View(projectTypes);
        }
    }
}

TheWaterProject2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TheWaterProject2.Models;
using TheWaterProject2.Models.ViewModels;

namespace TheWaterProject2.Controllers
{
    public class HomeController : Controller
    {
        public IWaterRepository _repo;
        public HomeController(IWaterRepository temp)
        {
            _repo = temp;
        }

        public IActionResult Index(int pageNum, string? projectType)
        {
            int pageSize = 2;

            var Blah = new ProjectsListViewModel
            {
                Projects = _repo.Projects
                    .Where(x => x.projectType == projectType || projectType == null)
                    .OrderBy(x => x.projectName)
                    .Skip((pageNum - 1) * pageSize)
                    .Take(pageSize),

                PaginationInfo = new PaginationInfo
                {
                    CurrentPage = pageNum,
                    ItemsPerPage = pageSize,
                    TotalItems = projectType == null ? _repo.Projects.Count() : _repo.Projects.Where(x => x.projectType == projectType).Count()
                    //If the project type is null, do the first thing, else do the second thing
                },

                CurrentProjectType = projectType
            };

            return View(Blah);
        }
    }
}

TheWaterProject2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model ProjectsListViewModel

    <h1>The Water Project</h1>

    @foreach (Project p in Model.Projects)
    {
        <partial name="ProjectSummary" model="p"/>
    }

<div page-model="@Model.PaginationInfo" page-action="Index" page-classes-enabled="true" page-class="btn" page-class-normal="btn-outline-dark" page-class-selected="btn-primary" page-url-projectType="@Model.CurrentProjectType" class="btn-group pull-right m-1"></div>

TheWaterProject2/Views/Shared/Components/ProjectTypes/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IQueryable<string>

<div class="d-grid gap-2">
    <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index" asp-route-projectType="" asp-route-pageNum ="">Home</a>

    @foreach(string pt in Model ?? Enumerable.Empty<string>())
    {
        <a class="btn @(pt == ViewBag.SelectedProjectType ? "btn-primary" : "btn-outline-secondary")" asp-controller="Home" asp-action="Index" asp-route-projectType="@pt" asp-route-pageNum="1">@pt</a>
    }
</div>

TheWaterProject2/Views/Shared/ProjectSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Project

<div class="card">
    <h3>
        @Model.projectName
        <span class="badge rounded-pill bg-primary text-white float-end"><small>Impact: @Model.projectImpactLevel served</small></span>
    </h3>
    <ul>
        <li>Project Type: @Model.projectType</li>
        <li>Regional Program: @Model.programName</li>
        <li>Impact: @Model.projectImpactLevel served</li>
        <li>Installation Date: @Model.projectInstallation</li>
        <li>Project Phase: @Model.projectPhase</li>
    </ul>
</div>

TheWaterProject2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TheWaterProject2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TheWaterProject2.styles.css" asp-append-version="true" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">THE WATER PROJECT</span>
    </div>

    <div class="row m-1 p-1">
        <div class="col-3">
            <vc:project-types></vc:project-types>
        </div>    
        <div class="container col-9">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>